from dataclasses import dataclass
from typing import Final
import numpy as np

# ============================================================
# Canonical Capital State Vector (112 Dimensions)
# ============================================================

VECTOR_DIMENSION: Final = 112


@dataclass(frozen=True)
class CapitalStateVector:
    """
    Canonical 112-dimensional control-state vector representing
    a single unit of private-market capital.
    """
    values: np.ndarray  # shape: (112,)

    def __post_init__(self):
        if self.values.shape != (VECTOR_DIMENSION,):
            raise ValueError(
                "CapitalStateVector must be exactly 112-dimensional"
            )


# ============================================================
# Vector Index Map (IMMUTABLE)
# ============================================================

# ---- Capital Structure Vectors (1–24)
INSTRUMENT_SENIORITY = 0
PREFERENCE_STACK_DEPTH = 1
DILUTION_EXPOSURE_COEFFICIENT = 2
WATERFALL_POSITION_INDEX = 3
OWNERSHIP_CONVERSION_PRIORITY = 4
ANTI_DILUTION_PROTECTION_LEVEL = 5
PAY_TO_PLAY_OBLIGATION = 6
SECURITY_CONVERSION_OPTIONALITY = 7
LIQUIDATION_PREFERENCE_MULTIPLE = 8
PARTICIPATION_RIGHTS_FLAG = 9
DIVIDEND_ACCRUAL_RATE = 10
REDEMPTION_RIGHTS_FLAG = 11
SECURITY_MATURITY_HORIZON = 12
CROSS_VEHICLE_ENTANGLEMENT_SCORE = 13
CAP_TABLE_PENETRATION_RATIO = 14
STRUCTURAL_SUBORDINATION_LEVEL = 15
INTERPOSITION_COMPLEXITY_SCORE = 16
CLAIM_ENFORCEABILITY_INDEX = 17
SECURITY_MUTABILITY_SCORE = 18
ECONOMIC_RIGHTS_ASYMMETRY = 19
CONTROL_RIGHTS_COUPLING = 20
EXIT_PRIORITY_CONSTRAINT = 21
CAPITAL_RECOVERY_SENIORITY = 22
STRUCTURAL_IRREVERSIBILITY_FLAG = 23

# ---- Obligation & Constraint Vectors (25–46)
CAPITAL_CALL_OBLIGATION_DENSITY = 24
REINVESTMENT_MANDATE_COEFFICIENT = 25
FOLLOW_ON_RESERVE_REQUIREMENT = 26
GP_DISCRETIONARY_OVERRIDE_EXPOSURE = 27
MANDATORY_PRO_RATA_PARTICIPATION = 28
CAPITAL_LOCKUP_INTENSITY = 29
DISTRIBUTION_RESTRICTION_LEVEL = 30
REDEPLOYMENT_LATENCY = 31
OBLIGATION_CASCADE_RISK = 32
UNFUNDED_COMMITMENT_RATIO = 33
CAPITAL_CALL_TIMING_VARIANCE = 34
DOWNSIDE_PROTECTION_OBLIGATION = 35
FEE_DRAG_OBLIGATION_RATE = 36
EXPENSE_PASS_THROUGH_EXPOSURE = 37
COVENANT_CONSTRAINT_DENSITY = 38
DEFAULT_TRIGGER_SENSITIVITY = 39
REMEDIAL_ACTION_LATENCY = 40
RESTRICTIVE_CONSENT_REQUIREMENT = 41
FORCED_LIQUIDITY_EVENT_EXPOSURE = 42
SIDE_LETTER_CONSTRAINT_SEVERITY = 43
CROSS_FUND_OBLIGATION_LINKAGE = 44
COVENANT_BREACH_PROPAGATION_RISK = 45

# ---- Temporal & Liquidity Vectors (47–68)
EXPECTED_LIQUIDITY_CENTROID = 46
LIQUIDITY_TIMING_VARIANCE = 47
EXIT_OPTIONALITY_DECAY_RATE = 48
TIME_TO_LIQUIDITY_MEDIAN = 49
LIQUIDITY_PATH_DEPENDENCE = 50
SECONDARY_MARKET_ACCESSIBILITY = 51
LIQUIDITY_EVENT_CLUSTERING_RISK = 52
TIME_COMPRESSION_FACTOR = 53
LIQUIDITY_ASYMMETRY_INDEX = 54
EARLY_EXIT_PENALTY_SEVERITY = 55
HOLDING_PERIOD_EXTENSION_RISK = 56
LIQUIDITY_STAGGERING_SCORE = 57
REALIZATION_TIMING_SKEW = 58
CAPITAL_FREEZE_PROBABILITY = 59
TIME_TO_DECISION_THRESHOLD = 60
EXIT_WINDOW_CONSTRAINT_SEVERITY = 61
LIQUIDITY_CONVEXITY = 62
EVENT_DRIVEN_TIMING_SHOCK_SENSITIVITY = 63
OPTIONALITY_HALF_LIFE = 64
ILLQUIDITY_DURATION_INDEX = 65
LIQUIDITY_REVERSIBILITY_SCORE = 66
ASYMMETRIC_LIQUIDITY_SKEW = 67

# ---- Control & Governance Vectors (69–88)
DECISION_AUTHORITY_ENTROPY = 68
BOARD_CONTROL_DISPERSION = 69
VETO_RIGHT_LATENCY = 70
GOVERNANCE_OVERRIDE_PROBABILITY = 71
CONSENT_CHAIN_COMPLEXITY = 72
CONTROL_RIGHT_ENFORCEMENT_SPEED = 73
GP_LP_POWER_ASYMMETRY = 74
BOARD_SEAT_ALLOCATION_RIGIDITY = 75
INFORMATION_RIGHTS_LATENCY = 76
CONTROL_RIGHTS_REVOCABILITY = 77
MANAGEMENT_DISCRETION_RANGE = 78
SILENT_CONTROL_LEAKAGE_SCORE = 79
GOVERNANCE_ESCALATION_THRESHOLD = 80
STAKEHOLDER_ALIGNMENT_FRICTION = 81
DECISION_DEADLOCK_PROBABILITY = 82
CONTROL_REVERSION_RISK = 83
OVERSIGHT_VISIBILITY_GAP = 84
FIDUCIARY_CONFLICT_INTENSITY = 85
CONTROL_EVENT_TRIGGER_SENSITIVITY = 86
GOVERNANCE_SHOCK_ABSORPTION = 87

# ---- Systemic & Correlation Vectors (89–104)
CROSS_PORTFOLIO_CONTAGION_COEFFICIENT = 88
MACRO_CORRELATION_AMPLIFIER = 89
GP_PLATFORM_COUPLING_STRENGTH = 90
CAPITAL_STRUCTURE_CORRELATION = 91
LIQUIDITY_SYNCHRONIZATION_RISK = 92
SYSTEMIC_STRESS_SENSITIVITY = 93
HIDDEN_DEPENDENCY_DENSITY = 94
PORTFOLIO_CONCENTRATION_PRESSURE = 95
FAILURE_MODE_OVERLAP_INDEX = 96
NON_LINEAR_PROPAGATION_FACTOR = 97
CROSS_VEHICLE_FEEDBACK_INTENSITY = 98
CASCADE_TRIGGER_PROBABILITY = 99
EXOGENOUS_SHOCK_TRANSLATION = 100
SYSTEMIC_RESILIENCE_SCORE = 101
INTERDEPENDENCE_VOLATILITY = 102
NON_OBVIOUS_DEPENDENCY_RESONANCE = 103

# ---- Exception & Stability Vectors (105–112)
MODEL_DEVIATION_MAGNITUDE = 104
STRUCTURAL_ANOMALY_FLAG = 105
LIQUIDITY_SHOCK_SENSITIVITY = 106
GOVERNANCE_BREACH_LIKELIHOOD = 107
CONSTRAINT_VIOLATION_INTENSITY = 108
EVENT_SEQUENCE_INSTABILITY = 109
CAPITAL_STATE_VOLATILITY = 110
CAPITAL_STATE_INSTABILITY_INDEX = 111
